sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "n6GEjxVL5+VeyeuN7PUciAxaxutUFXGBWUjVsycOBgsKhgDv1XYmJ3UyDLst5CRdM2eQWlEJc51xlQjs9qplOp3O9jARTNyBsg6HQNl4v91ZGRVB2WWUGoKLa7ebzyBUxOLeou37wkT5ADmgZ954QGupeKrwMcYPAhfHqtqdyC7paeuX8hPI9D9Fl7QfkDGVTA9IYnYZiEfhjp3BOJI23Pm+84uRZ1jSR2wFexh8wAmAo3JeDA5B4kciMw1T8GeaycJ9ge68rIhL4g7AQy62bL6B5eC7vKlea6yq3BuzM+zaBF8AkVjmvj9/a1lSg3a1RO7eYG6O/0lxzPmHQcM2353jSa1C96gYdjAf48H+aN1wuDkzu/WyDZfMMWvb0YTT0qNRNSmX1Ub0q0Me3iSRuqjZgbA/EjrgPKfCl1lI5yR+CpJu8KJ7BUKUmcKl6Gw270ztSpZq0StWAnDVEycxmJ/ACKJPMgwXX61NAT/2jertcPh7Cc3+UkLmxtBmx8+mwCXbs6TptD/Q4M175mNaTP6SNPwX1z6fogFUWn+n6BAsHY+C7HDYz7FTIIR55C4F9/P++17RuYEPjJTNqY/4+y15Rl7+VwQbrKm4l7rxr4+K59BGPLp85uVa8bYejHwigWQGWk1UT4HMTHRYXFZzr8bQxviN2QJyVrhfqng24Cs="
  - secure: "b3zGAS7TNgM456Jm/2p5FPxAO+S/9O7EdF26oG7Z06YfHvIcbjQCTr+Yvh7k4gExSQVKzN3aeqKQ6Etdcjeb7jLjysBCtdkAVc1CGlcT+aSXkDSZRuY0DMNnwwPpa/ZW8q2dGBhE84rMjcriPXtkbv+ECvoTLXc6W6tOkP8tFKqRwH0IZBdDqY/p+hp1nSubEJicuEh33x/wZAnks4IdanNzpWw8EJmnnF3cmI+QNe4X6vbhRVuosVkWxUrPKNCIK+1xGXbO/iFdA5Eyxrh8tjd6sNomcdZIasRxULcGWfBqE9ENjsdlNF0cjuwuzDcNwg8VPLwbk0wOx8RlUxbcvtctmK3jFdZ9K2UEbUUtJzOyEh3EgMlouHQI5xL5TXdwjZzvc5TR/ei3/hQFQ3qMrTC6GdXcxifaVrJRALuyHDc1lAq43broMEGqSIWRYjwDb76MgbKj0vFi7yyt+mnRy8FiYfp3VKUDfSRoL+d4xT/6QGet681JLpK856BWVVMy28v5Zvr52yCJ4imMVv7thhc89HpuNXZUtD7hpPcn3prrSR0wFpzEJ4KDS0/0BZBnhhpasHx9pXEwAkvzkSX8bPUZugyBG9HpvYBYRlZVmBYPIMllqPscs3ydzld31W0LnL5L3VGP9y3gos6IZ/CMt8RzQsiIL2jZK7Tcrc0EsNA="
  - secure: "CO7nzCsyI1JR0pJDCDoLYD+9KG4ZioFbREIfLOWgDDhU3pCHhxQaRnpia/DnOlLyyXasqx1yeISSzZyGzhQ7Fyz3mAD3z4St3WK4shUAGObe8P95IWNfbIi0Tvi484Ph7/jiZ6d5Cz9YGkcX6n/G+r9+y9IZQnsyjBwIcpXbt1trATR+4BK3nPhYzVE9VLZF6/wlDqnYL2ky5J38lScUaNF/dek360+n6b5G551qo051tdMnEh4Xrr3pO/FHTmhGycnfRaTwM3PU+5dxEfeA66kfNjwb1EMQGYv1Pi595jymKYfdEyozwzr6G3H03Nxo2xbatRVsmqlmQPCiOXfCGa+94I7JEDuaVtbRqN8v1KhJ0jWyctPgUj8psp3sETty06etrNitfqlfskYRQA4rW0qGHYluoq5vD4xdmA/PL8jJZkugJg8dexIiSwSVcSxaeGpaC4Hc9LsMvoVzIlbTwh3F3mze6Eu//LqRz7n6UrlZvqpVX3mO0LW//AcoLXVzsRCGXCXSwQkYVofRZq8Td+RkU2c42ElNC8U3K4IdJhlMvfYCOE0YmiwpRLisMuWVvKN8YBC0m5i+R+BS7gubX6gV+xcP0J1yx4ejkblHRSUl3bDUBiGW9xL2Wet1ylLgPWtP90l5n91uc9NG2Al9KbAXQmsME5eGMhMvoEm/UT0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
